version: '3'
services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=Welcome123
           - MYSQL_DATABASE=CRUD
           - MYSQL_USER=root
           - MYSQL_PASSWORD=Welcome123
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql

    restart: always
# backendserver
  springboot:
    image: java:8
    ports:
           - "8081"
    volumes:
         - /tmp
         - .Crud-Backy-0.0.1-SNAPSHOT.jar:/tmp/crud.jar
    command:  java -jar crud.jar

    links:
           - "db"
    depends_on:
           - "db"
    restart: always
#frontend
  angular:
    build: ./CRUD/
    links:
           - "springboot"
    depends_on:
           - "springboot"
    ports:
           - "80:80"